name: Mario Davalos
favicon: null
layout_spectrum: 0.7971236035227776
typography_spectrum: 0.9427359043620527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7963297113310546
  lightness: 0.5220715727191418
  saturation: 0.9013215380255133
  rhythmicContrast: 0.9917100206948817
purpose: []
